import { useCallback, useEffect, useState } from 'react';
import SafeMarkdown from './SafeMarkdown';
import { prepareContentImage } from '../lib/contentImage';

const tabs=['overview','messages','testimonials','lab','certifications','journal posts','photo stories','interests','now','section visibility','media','audit log'] as const;
const kinds:Record<string,string>={'lab':'lab','journal posts':'journal_post','photo stories':'photo_story','interests':'interest','now':'now'};
async function request(path:string,options:RequestInit={}){const r=await fetch(`/api/${path}`,{credentials:'same-origin',...options,headers:{...(options.body?{'Content-Type':'application/json','X-Admin-Action':'dashboard'}:{}),...options.headers}});const value=await r.json().catch(()=>({error:`HTTP ${r.status}`}));if(!r.ok)throw new Error(value.error||`HTTP ${r.status}`);return value}

export default function AdminDashboard(){const initial=(location.pathname.split('/')[1]||'overview').replace(/-/g,' ') as typeof tabs[number];const[tab,setTab]=useState(tabs.includes(initial)?initial:'overview');return <div className="admin-shell"><aside><a className="nav-brand" href="/"><span>owner<span className="host">@</span>hetshah.me</span></a><nav aria-label="Dashboard">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);history.replaceState({},'',`/${t.replace(/ /g,'-')}`)}}>{t}</button>)}</nav></aside><main><header><p className="section-kicker">private / access protected</p><h1>{tab}</h1></header><AdminPanel tab={tab}/></main></div>}

function AdminPanel({tab}:{tab:string}){if(tab==='overview')return <Overview/>;if(tab==='messages')return <Moderation type="messages"/>;if(tab==='testimonials')return <Moderation type="testimonials"/>;if(tab==='section visibility')return <Sections/>;if(tab==='media')return <Media/>;if(tab==='audit log')return <Audit/>;if(tab==='certifications')return <CertificationsAdmin/>;return <Entries kind={kinds[tab]}/>}
function useAdmin(path:string){const[data,setData]=useState<any>(null),[error,setError]=useState('');const load=useCallback(()=>request(path).then(setData).catch(e=>setError(e.message)),[path]);useEffect(()=>{void load()},[load]);return{data,error,load}}
function ErrorLine({children}:{children:string}){return children?<p className="admin-error">{children}</p>:null}

function Overview(){const{data,error}=useAdmin('overview');return <><ErrorLine>{error}</ErrorLine>{data&&<div className="metric-grid"><Metric label="Unread messages" value={data.unreadMessages}/><Metric label="Pending testimonials" value={data.pendingTestimonials}/><Metric label="Drafts" value={data.content.draft||0}/><Metric label="Media storage" value={data.mediaReady?'Ready':'Not connected'}/></div>}</>}
function Metric({label,value}:{label:string;value:any}){return <div className="metric"><strong>{value}</strong><span>{label}</span></div>}

function Moderation({type}:{type:'messages'|'testimonials'}){const{data,error,load}=useAdmin(type);async function update(item:any,value:string){await request(`${type}/${item.id}`,{method:'PATCH',body:JSON.stringify(type==='messages'?{state:value}:{status:value,source:item.source})});load()}return <><ErrorLine>{error}</ErrorLine><div className="admin-list">{data?.map((x:any)=><article key={`${x.source||''}-${x.id}`}><h2>{x.name}</h2><p>{x.email} · {x.role||x.createdAt}</p>{type==='testimonials'&&x.source==='submission'&&<img className="admin-thumb" src={`/api/testimonials/${x.id}/photo`} alt={`Portrait submitted by ${x.name}`}/>}<p className="pre">{x.message}</p>{type==='testimonials'&&<p>{x.company} — {x.experience}<br/>{x.relationship}</p>}<div className="admin-actions">{(type==='messages'?['read','archived','trash','unread']:['approved','rejected',...(x.source==='legacy'?[]:['pending'])]).map(v=><button onClick={()=>void update(x,v)} key={v}>{v}</button>)}</div></article>)}</div></>}

const empty={title:'',slug:'',summary:'',bodyMarkdown:'',category:'',difficulty:'',tags:'',tools:'',status:'draft',position:0,revision:1};
function Entries({kind}:{kind:string}){const{data,error,load}=useAdmin('entries');const[current,setCurrent]=useState<any>({...empty,kind});const[notice,setNotice]=useState('');const items=(data||[]).filter((x:any)=>x.kind===kind);async function save(){setNotice('');try{const result=await request(current.id?`entries/${current.id}`:'entries',{method:current.id?'PUT':'POST',body:JSON.stringify({...current,tags:String(current.tags||'').split(',').map((v:string)=>v.trim()).filter(Boolean),tools:String(current.tools||'').split(',').map((v:string)=>v.trim()).filter(Boolean),references:[]})});setNotice('Saved.');load();if(!current.id)setCurrent({...current,id:result.id,revision:1})}catch(e){setNotice((e as Error).message)}}return <div className="editor-layout"><section><p className="admin-warning">Before publishing, remove employer/customer names, internal addresses, credentials, proprietary diagrams, real targets and confidential incident details.</p><button className="btn-term btn-term--sm" onClick={()=>setCurrent({...empty,kind})}>New</button><div className="admin-list compact">{items.map((x:any)=><button key={x.id} onClick={()=>setCurrent({...x,tags:'',tools:parseList(x.tools_json).join(', ')})}><strong>{x.title}</strong><span>{x.status} · r{x.revision}</span></button>)}</div></section><section className="editor"><ErrorLine>{error||notice}</ErrorLine><label>Title<input value={current.title} onChange={e=>setCurrent({...current,title:e.target.value})}/></label><label>Slug<input value={current.slug} disabled={kind==='now'} placeholder={kind==='now'?'now':''} onChange={e=>setCurrent({...current,slug:e.target.value})}/></label><label>Summary<textarea value={current.summary} onChange={e=>setCurrent({...current,summary:e.target.value})}/></label><label>Category<input value={current.category||''} onChange={e=>setCurrent({...current,category:e.target.value})}/></label><label>Tags, comma separated<input value={current.tags||''} onChange={e=>setCurrent({...current,tags:e.target.value})}/></label><label>Tools, comma separated<input value={current.tools||''} onChange={e=>setCurrent({...current,tools:e.target.value})}/></label><label>Markdown<textarea className="code-input" value={current.bodyMarkdown??current.body_markdown??''} onChange={e=>setCurrent({...current,bodyMarkdown:e.target.value})}/></label><label>State<select value={current.status} onChange={e=>setCurrent({...current,status:e.target.value})}><option>draft</option><option>published</option><option>trash</option></select></label><button className="btn-term" onClick={()=>void save()}>Save revision</button>{current.id&&<EntryMedia entryId={current.id}/>}<h2>Preview</h2><div className="preview"><SafeMarkdown>{current.bodyMarkdown??current.body_markdown??''}</SafeMarkdown></div></section></div>}
function parseList(v:any){try{return JSON.parse(v||'[]')}catch{return[]}}
function EntryMedia({entryId}:{entryId:string}){const{data:all}=useAdmin('media');const{data:attached,load}=useAdmin(`entries/${entryId}/media`);const[notice,setNotice]=useState('');const selected=new Map((attached||[]).map((x:any)=>[x.id,x]));async function toggle(media:any,checked:boolean){const items=checked?[...(attached||[]),{id:media.id,altText:'Describe this image',caption:''}]:(attached||[]).filter((x:any)=>x.id!==media.id);try{await request(`entries/${entryId}/media`,{method:'PUT',body:JSON.stringify({items})});load()}catch(e){setNotice((e as Error).message)}}async function update(item:any,key:string,value:string){const items=(attached||[]).map((x:any)=>x.id===item.id?{...x,[key]:value}:x);await request(`entries/${entryId}/media`,{method:'PUT',body:JSON.stringify({items})});load()}return <div><h2>Ordered images</h2><ErrorLine>{notice}</ErrorLine>{all?.items?.map((m:any)=>{const item=selected.get(m.id) as any;return <div className="media-order-row" key={m.id}><label><input type="checkbox" checked={!!item} onChange={e=>void toggle(m,e.target.checked)}/>{m.id.slice(0,8)} · {Math.ceil(m.byteSize/1024)} KB</label>{item&&<><input aria-label="Alt text" value={item.altText} onChange={e=>void update(item,'altText',e.target.value)}/><input aria-label="Caption" placeholder="Optional caption" value={item.caption||''} onChange={e=>void update(item,'caption',e.target.value)}/></>}</div>})}</div>}

function Sections(){const{data,error,load}=useAdmin('sections');async function toggle(x:any){try{await request(`sections/${x.name}`,{method:'PATCH',body:JSON.stringify({enabled:!x.enabled})});load()}catch(e){alert((e as Error).message)}}return <><ErrorLine>{error}</ErrorLine><div className="admin-list">{data?.map((x:any)=><article key={x.name}><h2>{x.name}</h2><p>{x.enabled?'Visible when published':'Hidden from visitors'}</p><button onClick={()=>void toggle(x)}>{x.enabled?'Disable':'Enable'}</button></article>)}</div></>}
function Media(){const{data,error,load}=useAdmin('media');const[notice,setNotice]=useState('');async function upload(e:any){e.preventDefault();const form=e.currentTarget,raw=new FormData(form),file=raw.get('file');try{if(!(file instanceof File))throw new Error('Choose an image.');setNotice('Optimizing locally…');const optimized=await prepareContentImage(file,raw.get('diagram')==='on');const f=new FormData();f.set('file',optimized);f.set('alt',String(raw.get('alt')||''));const r=await fetch('/api/media',{method:'POST',credentials:'same-origin',headers:{'X-Admin-Action':'media-upload'},body:f});const j=await r.json();if(!r.ok)throw new Error(j.error);setNotice('Uploaded with metadata removed.');form.reset();load()}catch(err){setNotice((err as Error).message)}}async function importGoogle(e:any){e.preventDefault();const form=e.currentTarget,b=Object.fromEntries(new FormData(form));try{await request('media/import',{method:'POST',body:JSON.stringify(b)});setNotice('Imported. The temporary Google token was not stored.');form.reset();load()}catch(err){setNotice((err as Error).message)}}return <><ErrorLine>{error||notice}</ErrorLine>{data&&!data.ready&&<p>R2 is not connected yet. Activate R2, create the private <code>portfolio-media</code> Standard bucket, then add its Worker binding.</p>}<form className="editor" onSubmit={upload}><label>Image (JPG, PNG or WebP; source max 20 MB)<input type="file" name="file" accept="image/jpeg,image/png,image/webp" required/></label><label>Alt text<input name="alt" required/></label><label><input type="checkbox" name="diagram"/> Preserve diagram detail</label><button className="btn-term">Optimize and upload</button></form><h2>Google import</h2><p>OAuth/Picker must be configured first. Authorization tokens are used once and never saved.</p><form className="editor" onSubmit={importGoogle}><label>Drive file or Photos Picker URL<input name="sourceUrl" type="url" required/></label><label>Temporary Google access token<input name="accessToken" type="password" required/></label><label>Alt text<input name="alt" required/></label><button className="btn-term">Import privately</button></form><p>{data?.items?.length||0} stored objects</p></>}
function Audit(){const{data,error}=useAdmin('audit');return <><ErrorLine>{error}</ErrorLine><div className="admin-list compact">{data?.map((x:any,i:number)=><article key={i}><strong>{x.action}</strong><span>{x.resourceType} {x.resourceId||''} · {new Date(x.createdAt).toLocaleString()}</span></article>)}</div></>}
function CertificationsAdmin(){const{data,error,load}=useAdmin('certifications');const[current,setCurrent]=useState<any>({name:'',issuer:'',state:'planned',revision:1});async function save(){await request(current.id?`certifications/${current.id}`:'certifications',{method:current.id?'PUT':'POST',body:JSON.stringify(current)});setCurrent({name:'',issuer:'',state:'planned',revision:1});load()}return <div className="editor-layout"><div className="admin-list compact">{data?.map((x:any)=><button onClick={()=>setCurrent(x)} key={x.id}>{x.name}</button>)}</div><div className="editor"><ErrorLine>{error}</ErrorLine><label>Name<input value={current.name} onChange={e=>setCurrent({...current,name:e.target.value})}/></label><label>Issuer<input value={current.issuer} onChange={e=>setCurrent({...current,issuer:e.target.value})}/></label><label>State<select value={current.state} onChange={e=>setCurrent({...current,state:e.target.value})}><option value="planned">planned</option><option value="in_progress">in progress</option><option value="earned">earned</option></select></label><label>Credential URL<input value={current.credentialUrl||current.credential_url||''} onChange={e=>setCurrent({...current,credentialUrl:e.target.value})}/></label><button className="btn-term" onClick={()=>void save()}>Save</button></div></div>}
