import { useEffect, useMemo, useState } from 'react';
import { apiUrl } from '../lib/api';
import SafeMarkdown from './SafeMarkdown';
import SectionHeading from './SectionHeading';

export type Entry={id:string;title:string;slug:string;summary:string;bodyMarkdown?:string;category?:string;difficulty?:string;tags?:string[];tools?:string[];references?:Array<{label?:string;url?:string}>;repositoryUrl?:string;demoUrl?:string;publishedAt?:string;readingMinutes?:number;media?:Array<{id:string;url:string;altText:string;caption?:string;width?:number;height?:number}>};
function useData<T>(path:string){const[data,setData]=useState<T|null>(null),[error,setError]=useState(false);useEffect(()=>{const c=new AbortController();setError(false);fetch(apiUrl(path),{signal:c.signal}).then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(e=>{if(e?.name!=='AbortError')setError(true)});return()=>c.abort()},[path]);return{data,error}}

function Listing({kind,title,command,detailBase}:{kind:string;title:string;command:string;detailBase:string}){
  const{data,error}=useData<Entry[]>(`content/${kind}`);const[tag,setTag]=useState('');const tags=useMemo(()=>[...new Set((data||[]).flatMap(e=>e.tags||[]))].sort(),[data]);const items=(data||[]).filter(e=>!tag||e.tags?.includes(tag));
  return <section className="section"><div className="container"><SectionHeading index="04" command={command} comment={title}/>{tags.length>0&&<div className="filter-row"><button className={!tag?'active':''} onClick={()=>setTag('')}>all</button>{tags.map(t=><button className={tag===t?'active':''} onClick={()=>setTag(t)} key={t}>{t}</button>)}</div>}{error?<p>Could not load this section.</p>:data===null?<p className="term-muted">Loading…</p>:items.length===0?<p>No published entries yet.</p>:<div className="content-grid">{items.map(e=><article className="content-card" key={e.id}><p className="section-kicker">{e.category||kind.replace('_',' ')}</p><h2><a href={`${detailBase}/${e.slug}`}>{e.title}</a></h2><p>{e.summary}</p><div className="tag-row">{e.tags?.map(t=><span key={t}>{t}</span>)}</div></article>)}</div>}</div></section>
}
export const Lab=()=> <Listing kind="lab" title="sanitized field notes" command="ls ./lab" detailBase="/lab"/>;
export const Journal=()=> <Listing kind="journal_post" title="essays and short notes" command="ls ./journal" detailBase="/journal/posts"/>;
export const PhotoStories=()=> <Listing kind="photo_story" title="photo stories" command="ls ./journal/photos" detailBase="/journal/photos"/>;
export function Interests(){const{data,error}=useData<Entry[]>('content/interest');return <section className="section"><div className="container article-wrap"><SectionHeading index="05" command="cat interests.md" comment="things I keep returning to"/>{error?<p>Could not load interests.</p>:data?.map(item=><article className="content-card mb-3" key={item.id}><h2>{item.title}</h2><p>{item.summary}</p>{item.bodyMarkdown&&<SafeMarkdown>{item.bodyMarkdown}</SafeMarkdown>}</article>)}</div></section>}

export function EntryPage({kind,slug}:{kind:string;slug:string}){const{data,error}=useData<Entry>(`content/${kind}/${encodeURIComponent(slug)}`);useEffect(()=>{if(data){document.title=`${data.title} — Het Shah`;setHead('link','canonical',location.href);setHead('meta','description',data.summary);setHead('meta','og:title',data.title,true);setHead('meta','og:description',data.summary,true);setHead('meta','og:url',location.href,true)}},[data]);if(error)return <NotFound/>;if(!data)return <section className="section"><div className="container">Loading…</div></section>;return <article className="section"><div className="container article-wrap"><p className="section-kicker">{data.category} · {data.readingMinutes} min read</p><h1 className="section-title">{data.title}</h1><p className="section-sub">{data.summary}</p><div className="tag-row">{data.tags?.map(t=><span key={t}>{t}</span>)}</div>{data.media&&data.media.length>0&&<div className="media-gallery">{data.media.map(m=><figure key={m.id}><img src={m.url} alt={m.altText} loading="lazy" width={m.width} height={m.height}/>{m.caption&&<figcaption>{m.caption}</figcaption>}</figure>)}</div>}<SafeMarkdown>{data.bodyMarkdown||''}</SafeMarkdown>{data.tools&&data.tools.length>0&&<p><strong>Tools:</strong> {data.tools.join(', ')}</p>}<div className="entry-links">{data.repositoryUrl&&<a href={data.repositoryUrl} rel="noopener noreferrer">Repository</a>}{data.demoUrl&&<a href={data.demoUrl} rel="noopener noreferrer">Demo</a>}</div>{data.references&&data.references.length>0&&<section><h2>References</h2><ul>{data.references.map((r,i)=><li key={i}><a href={r.url} rel="noopener noreferrer">{r.label||r.url}</a></li>)}</ul></section>}</div></article>}
function setHead(tag:'meta'|'link',name:string,value:string,property=false){const selector=tag==='link'?`link[rel="${name}"]`:`meta[${property?'property':'name'}="${name}"]`;let node=document.querySelector(selector) as HTMLMetaElement|HTMLLinkElement|null;if(!node){node=document.createElement(tag);if(tag==='link')(node as HTMLLinkElement).rel=name;else node.setAttribute(property?'property':'name',name);document.head.append(node)}if(tag==='link')(node as HTMLLinkElement).href=value;else(node as HTMLMetaElement).content=value}

export function Certifications(){const{data,error}=useData<Array<any>>('certifications');return <section className="section"><div className="container"><SectionHeading index="04" command="cat certifications.json" comment="learning milestones"/>{error?<p>Could not load certifications.</p>:<div className="content-grid">{data?.map(c=><article className="content-card" key={c.id}><p className="section-kicker">{c.state.replace('_',' ')}</p><h2>{c.name}</h2><p>{c.issuer}</p>{c.credentialUrl&&<a href={c.credentialUrl}>Verify credential</a>}</article>)}</div>}</div></section>}
export const Now=()=> <EntryPage kind="now" slug="now"/>;
export const NotFound=()=> <section className="section"><div className="container"><h1>Page not found</h1><p>That path does not exist or has not been published.</p><a className="btn-term" href="/">Return home</a></div></section>;
