/**
 * Turns the JSON in db/data/ into db/seed.sql.
 *
 *   node db/generate-seed.mjs
 *
 * Deterministic: ids carried over from MongoDB are reused verbatim, and ids for
 * records that never existed there are derived from a hash of their natural key,
 * so re-running produces identical SQL.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, 'data');

const read = (name) => JSON.parse(readFileSync(join(dataDir, name), 'utf8'));

/** SQL string literal, or NULL for empty/absent values. */
const sql = (value) => {
  if (value === null || value === undefined || value === '') return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
};

const num = (value) => (Number.isFinite(value) ? String(value) : 'NULL');

/** Stable 24-char hex id, matching the shape of the migrated ObjectIds. */
const derivedId = (key) => createHash('sha1').update(key).digest('hex').slice(0, 24);

const MONTHS = {
  january: 1, february: 2, march: 3, april: 4, may: 5, june: 6,
  july: 7, august: 8, september: 9, october: 10, november: 11, december: 12,
};

/**
 * Best-effort "YYYY-MM-DD" from the free-text event dates, which arrive in at
 * least four shapes ("September 13-14,2025", "August 11–12, 2025",
 * "21st - 23rd March 2025"). Uses the first day of the range.
 */
function toSortDate(raw) {
  const text = String(raw)
    .replace(/[\u2012-\u2015]/g, '-')
    .replace(/(\d+)(st|nd|rd|th)/gi, '$1');

  const month = text.match(/(january|february|march|april|may|june|july|august|september|october|november|december)/i);
  const year = text.match(/\b(\d{4})\b/);
  if (!month || !year) return null;

  const day = text.replace(/\b\d{4}\b/, '').match(/\b(\d{1,2})\b/);
  const pad = (n) => String(n).padStart(2, '0');
  return `${year[1]}-${pad(MONTHS[month[1].toLowerCase()])}-${pad(day ? Number(day[1]) : 1)}`;
}

const lines = [
  '-- Generated by db/generate-seed.mjs — do not edit by hand.',
  '-- Regenerate with: node db/generate-seed.mjs',
  '',
  'DELETE FROM project_screenshots;',
  'DELETE FROM project_tech;',
  'DELETE FROM projects;',
  'DELETE FROM testimonials;',
  'DELETE FROM hackathon_tech;',
  'DELETE FROM hackathons;',
  'DELETE FROM experience_highlights;',
  'DELETE FROM experience_skills;',
  'DELETE FROM experience;',
  '',
];

// ------------------------------------------------------------------ projects
const projects = read('projects.json');
lines.push('-- projects');
projects.forEach((p, i) => {
  const id = p._id ?? derivedId(`project:${p.title}`);
  lines.push(
    `INSERT INTO projects (id, title, description, long_description, image, github_url, position) VALUES (${sql(id)}, ${sql(p.title)}, ${sql(p.description)}, ${sql(p.longDescription ?? '')}, ${sql(p.image)}, ${sql(p.githubUrl)}, ${i});`
  );
  (p.techStack ?? []).forEach((tech, j) =>
    lines.push(`INSERT INTO project_tech (project_id, position, tech) VALUES (${sql(id)}, ${j}, ${sql(tech)});`)
  );
  (p.screenshots ?? []).forEach((url, j) =>
    lines.push(`INSERT INTO project_screenshots (project_id, position, url) VALUES (${sql(id)}, ${j}, ${sql(url)});`)
  );
});
lines.push('');

// -------------------------------------------------------------- testimonials
const testimonials = read('testimonials.json');
lines.push('-- testimonials');
testimonials.forEach((t, i) => {
  const id = t._id ?? derivedId(`testimonial:${t.name}:${t.role}`);
  lines.push(
    `INSERT INTO testimonials (id, name, role, avatar, text, position) VALUES (${sql(id)}, ${sql(t.name)}, ${sql(t.role)}, ${sql(t.avatar)}, ${sql(t.text)}, ${i});`
  );
});
lines.push('');

// ---------------------------------------------------------------- hackathons
const hackathons = read('hackathons.json');
lines.push('-- hackathons');
hackathons.forEach((h) => {
  const id = h._id ?? derivedId(`hackathon:${h.title}`);
  const sortDate = toSortDate(h.date);
  if (!sortDate) console.warn(`[seed] could not parse date for "${h.title}": ${h.date}`);
  lines.push(
    `INSERT INTO hackathons (id, title, event_date, duration, image, description, achievement, team_size, git_url, project_url, video_url, sort_date) VALUES (${sql(id)}, ${sql(h.title)}, ${sql(h.date)}, ${sql(h.duration)}, ${sql(h.image)}, ${sql(h.description)}, ${sql(h.achievement)}, ${num(h.teamSize)}, ${sql(h.gitUrl)}, ${sql(h.projectUrl)}, ${sql(h.videoUrl)}, ${sql(sortDate)});`
  );
  (h.techStack ?? []).forEach((tech, j) =>
    lines.push(`INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES (${sql(id)}, ${j}, ${sql(tech)});`)
  );
});
lines.push('');

// ---------------------------------------------------------------- experience
const experience = read('experience.json');
lines.push('-- experience');
experience.forEach((e) => {
  const id = e._id ?? derivedId(`experience:${e.company}:${e.role}`);
  lines.push(
    `INSERT INTO experience (id, role, company, company_url, employment_type, location, start_date, end_date, summary) VALUES (${sql(id)}, ${sql(e.role)}, ${sql(e.company)}, ${sql(e.companyUrl)}, ${sql(e.employmentType)}, ${sql(e.location)}, ${sql(e.startDate)}, ${sql(e.endDate)}, ${sql(e.summary)});`
  );
  (e.highlights ?? []).forEach((highlight, j) =>
    lines.push(`INSERT INTO experience_highlights (experience_id, position, highlight) VALUES (${sql(id)}, ${j}, ${sql(highlight)});`)
  );
  (e.skills ?? []).forEach((skill, j) =>
    lines.push(`INSERT INTO experience_skills (experience_id, position, skill) VALUES (${sql(id)}, ${j}, ${sql(skill)});`)
  );
});
lines.push('');

writeFileSync(join(here, 'seed.sql'), lines.join('\n'));

console.log(
  `[seed] wrote db/seed.sql — ${projects.length} projects, ${testimonials.length} testimonials, ` +
    `${hackathons.length} hackathons, ${experience.length} experience`
);
