-- Generated by db/generate-seed.mjs — do not edit by hand.
-- Regenerate with: node db/generate-seed.mjs

DELETE FROM project_screenshots;
DELETE FROM project_tech;
DELETE FROM projects;
DELETE FROM testimonials;
DELETE FROM hackathon_tech;
DELETE FROM hackathons;
DELETE FROM experience_highlights;
DELETE FROM experience_skills;
DELETE FROM experience;

-- projects
INSERT INTO projects (id, title, description, long_description, image, github_url, position) VALUES ('68d02c84970b5b3ab683d8fd', 'StyleSync-AI Powered Personal Fashion Recommender', 'AI-powered personal stylist that recommends outfits based on your photo.', 'If fashion were an exam, we would probably score in negative marks 🤦‍♂️😂

So me and my friend Aayush Pandya decided to let AI handle our style sense, and that’s how StyleSync came to life 👗✨

Upload a photo, and our model analyzes it to detect your age, gender & skin tone, then recommends outfits that actually suit you — your personal stylist, but smarter (and less judgmental 😅). For this, we trained the model on 44,000 images from the FashionCLIP dataset available on Kaggle, using CNNs to ensure accurate predictions.

We also built:
✅ Fashion fest explorer (India)
✅ Smooth shopping + order emails via Nodemailer
✅ Admin panel to manage shop, events & queries', 'https://defiant-lavender-ypeckrufll.edgeone.app/StyleSyncBanner.jpg', 'https://github.com/ShahHet2812/TrendyWare', 0);
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d02c84970b5b3ab683d8fd', 0, 'React');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d02c84970b5b3ab683d8fd', 1, 'Express');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d02c84970b5b3ab683d8fd', 2, 'Django');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d02c84970b5b3ab683d8fd', 3, 'MongoDB Atlas');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d02c84970b5b3ab683d8fd', 4, 'CNN');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d02c84970b5b3ab683d8fd', 5, 'Nodemailer');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d02c84970b5b3ab683d8fd', 0, 'https://defiant-lavender-ypeckrufll.edgeone.app/ss1.jpg');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d02c84970b5b3ab683d8fd', 1, 'https://defiant-lavender-ypeckrufll.edgeone.app/ss2.jpg');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d02c84970b5b3ab683d8fd', 2, 'https://defiant-lavender-ypeckrufll.edgeone.app/ss3.jpg');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d02c84970b5b3ab683d8fd', 3, 'https://defiant-lavender-ypeckrufll.edgeone.app/ss4.jpg');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d02c84970b5b3ab683d8fd', 4, 'https://defiant-lavender-ypeckrufll.edgeone.app/ss5.jpg');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d02c84970b5b3ab683d8fd', 5, 'https://defiant-lavender-ypeckrufll.edgeone.app/ss6.jpg');
INSERT INTO projects (id, title, description, long_description, image, github_url, position) VALUES ('68d0376c2f34c616e517b141', 'SatvaFarm: Plant Disease Detection and Government Scheme Portal', 'A web application to help farmers detect plant diseases by uploading images and to provide information about relevant government schemes. It also includes a knowledge base with articles about agriculture.', 'AgriCare is a comprehensive platform for farmers. It leverages machine learning for plant disease detection. Users can upload images of their plants and get instant feedback on their health. The application also serves as a portal for discovering and applying for government schemes related to agriculture. A rich knowledge base with articles and guides is available to keep farmers informed about the latest agricultural practices. The platform requires user authentication and has a verification system using ID proofs. The frontend is a modern single-page application built with React.', 'https://defiant-lavender-ypeckrufll.edgeone.app/SatvaFarmBanner.jpg', 'https://github.com/ShahHet2812/SatvaFarm', 1);
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d0376c2f34c616e517b141', 0, 'Django');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d0376c2f34c616e517b141', 1, 'Django REST Framework');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d0376c2f34c616e517b141', 2, 'React');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d0376c2f34c616e517b141', 3, 'Python');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d0376c2f34c616e517b141', 4, 'JavaScript');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d0376c2f34c616e517b141', 5, 'Tailwind CSS');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d0376c2f34c616e517b141', 6, 'Vite');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d0376c2f34c616e517b141', 0, 'https://defiant-lavender-ypeckrufll.edgeone.app/sf1.jpg');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d0376c2f34c616e517b141', 1, 'https://defiant-lavender-ypeckrufll.edgeone.app/sf2.jpg');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d0376c2f34c616e517b141', 2, 'https://defiant-lavender-ypeckrufll.edgeone.app/sf3.jpg');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d0376c2f34c616e517b141', 3, 'https://defiant-lavender-ypeckrufll.edgeone.app/sf4.jpg');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d0376c2f34c616e517b141', 4, 'https://defiant-lavender-ypeckrufll.edgeone.app/sf5.jpg');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d0376c2f34c616e517b141', 5, 'https://defiant-lavender-ypeckrufll.edgeone.app/sf6.jpg');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d0376c2f34c616e517b141', 6, 'https://defiant-lavender-ypeckrufll.edgeone.app/sf7.jpg');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d0376c2f34c616e517b141', 7, 'https://defiant-lavender-ypeckrufll.edgeone.app/sf8.jpg');
INSERT INTO projects (id, title, description, long_description, image, github_url, position) VALUES ('68d035182f34c616e517b13f', 'Personal Health Tracker', 'A Java-based application to track health, book appointments, calculate BMI, and maintain patient records.', 'A Java-based Personal Health Tracker system that allows users to monitor and manage their fitness, nutrition, and overall wellness through personalized data tracking and analytics.

Key Features:
- User Profile Management: Create and customize individual health profiles with personal details and goals.
- Activity Tracking: Log daily physical activities like steps, workouts, and calories burned.
- Health Metrics Dashboard: View real-time health metrics like weight, BMI, heart rate, and sleep patterns.
- Reminders & Notifications: Receive reminders for workouts, meals, hydration, and medication.', 'https://defiant-lavender-ypeckrufll.edgeone.app/Tracker.jpg', 'https://github.com/ShahHet2812/HealthTracker', 2);
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d035182f34c616e517b13f', 0, 'Java');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d035182f34c616e517b13f', 1, 'Swing');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d035182f34c616e517b13f', 2, 'API');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d035182f34c616e517b13f', 3, 'Queue');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d035182f34c616e517b13f', 4, 'Stack');
INSERT INTO project_tech (project_id, position, tech) VALUES ('68d035182f34c616e517b13f', 5, 'PHP');
INSERT INTO project_screenshots (project_id, position, url) VALUES ('68d035182f34c616e517b13f', 0, 'https://defiant-lavender-ypeckrufll.edgeone.app/HealthTracker.png');

-- testimonials
INSERT INTO testimonials (id, name, role, avatar, text, position) VALUES ('68cc3c3590dcd192e5e7b9c3', 'Aayush Pandya', '2-time Hackathon Partner and Classmate', 'https://testimonials.edgeone.app/aayush.jpg', 'Your invaluable co-operation in the highly significant project presented by our university was very much appreciated. Your intellectual capabilities were of great help in completion of the project.Your quick responses during the presentation certainly solidified a respectable score which helped us with end term results', 0);
INSERT INTO testimonials (id, name, role, avatar, text, position) VALUES ('68cc3c3590dcd192e5e7b9c4', 'Moksh Kothari', 'Classmate', 'https://testimonials.edgeone.app/moksh.jpg', 'The kind of college-mate on whom one can trust. Best encouragement provider and always ready to support the group.', 1);
INSERT INTO testimonials (id, name, role, avatar, text, position) VALUES ('68cc3c3590dcd192e5e7b9c5', 'Yashesh Mehta', '1-time Hackathon Partner and Classmate', 'https://testimonials.edgeone.app/Yashesh.png', 'Working with Het on our college project was a great experience for me. He was not only a good team-mate, but also a good supporter. With his quick intellect and problem solving skills, he always found out a way in any kind of problems. He is a quick learner and is always motivates others to do the best out of them. He also has good analytical thinking which helped us a lot in the project. I''m grateful that I''ve got a chance to work with him.', 2);

-- hackathons
INSERT INTO hackathons (id, title, event_date, duration, image, description, achievement, team_size, git_url, project_url, video_url, sort_date) VALUES ('68cc361d766beb82d9905f55', 'Hackovate 2025', 'September 13-14,2025', '36 hours', 'https://hackathon.edgeone.app/LJ.jpg', 'An AI/ML-powered Cattle Analytics Platform built in 36 hours. It predicts milk yield, detects cattle diseases, and provides multilingual veterinary guidance. The solution integrates XGBoost regression and classification models, explainability with SHAP, PDF report generation, and an AI chatbot specialized in cattle health.', 'Built and deployed a complete AI-driven cattle monitoring solution in 36 hours.', 3, 'https://github.com/ShahHet2812/Hackovate', 'https://codeblooded.streamlit.app', NULL, '2025-09-13');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc361d766beb82d9905f55', 0, 'Python');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc361d766beb82d9905f55', 1, 'Streamlit');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc361d766beb82d9905f55', 2, 'XGBoost');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc361d766beb82d9905f55', 3, 'scikit-learn');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc361d766beb82d9905f55', 4, 'pandas');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc361d766beb82d9905f55', 5, 'NumPy');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc361d766beb82d9905f55', 6, 'Matplotlib');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc361d766beb82d9905f55', 7, 'SHAP');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc361d766beb82d9905f55', 8, 'ReportLab');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc361d766beb82d9905f55', 9, 'LangChain');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc361d766beb82d9905f55', 10, 'Gemini API');
INSERT INTO hackathons (id, title, event_date, duration, image, description, achievement, team_size, git_url, project_url, video_url, sort_date) VALUES ('68cc3148766beb82d9905f52', 'Odoo Hackathon 2025', 'August 11–12, 2025', '24 hours', 'https://hackathon.edgeone.app/odoo.jpg', 'Our team made it to the offline round of Odoo Hackathon 2025 after clearing the online round with a rank of 335 out of 2000+ registrations. We spent 24 intense hours at Gandhinagar collaborating, coding, and delivering a complete project as per the problem statement. It was a thrilling experience filled with teamwork, late-night hustle, and lots of learning.', 'Advanced to offline round and delivered a full solution.', 3, 'https://github.com/ShahHet2812/Odoo-2k25', 'https://quick-court-two.vercel.app/', 'https://drive.google.com/file/d/1xC402o-EfBtExk84rPTkNfECj81tOtv2/view?usp=drive_link', '2025-08-11');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc3148766beb82d9905f52', 0, 'MERN Stack');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc3148766beb82d9905f52', 1, 'Web Development');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc3148766beb82d9905f52', 2, 'Hackathon Problem-Solving');
INSERT INTO hackathons (id, title, event_date, duration, image, description, achievement, team_size, git_url, project_url, video_url, sort_date) VALUES ('68cc2f75766beb82d9905f50', 'HackNUthon 2025', 'March 29–31, 2025', '3 days', 'https://hackathon.edgeone.app/nirma.jpg', 'We built a Smart Kitchen System for Petpooja that identifies food objects using Computer Vision, links to an inventory dashboard for real-time stock tracking, implements a waste management system powered by Machine Learning, and suggests recipes using the MealDB API by prioritizing ingredients nearing expiry. The project aimed to reduce food waste and optimize kitchen management with AI-driven solutions.', 'Built an AI-powered Smart Kitchen prototype in 3 days.', 4, 'https://github.com/swapnil05patel/TechGPT', NULL, 'https://youtu.be/jBrCSYz8kAE', '2025-03-29');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc2f75766beb82d9905f50', 0, 'Computer Vision');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc2f75766beb82d9905f50', 1, 'Machine Learning');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc2f75766beb82d9905f50', 2, 'MealDB API');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc2f75766beb82d9905f50', 3, 'Dashboard Development');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68cc2f75766beb82d9905f50', 4, 'AI-driven Systems');
INSERT INTO hackathons (id, title, event_date, duration, image, description, achievement, team_size, git_url, project_url, video_url, sort_date) VALUES ('68ce896274267852dcc20716', 'Economania 2025 - FinTech Hackathon', '21st - 23rd March 2025', '3 Days', 'https://hackathon.edgeone.app/PDEU.jpg', 'Prototype EV Rental Management System with KYC verification, booking flow, and responsive design. Focused mainly on frontend as our first hackathon.', 'First hackathon — gained confidence presenting and tackling challenges.', 4, 'https://github.com/Yashesh1195/EV-Rental-Management-System-HYMN-EV-Rentals', NULL, NULL, '2025-03-21');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68ce896274267852dcc20716', 0, 'HTML5');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68ce896274267852dcc20716', 1, 'CSS3');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68ce896274267852dcc20716', 2, 'JavaScript');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68ce896274267852dcc20716', 3, 'Bootstrap 5.3');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68ce896274267852dcc20716', 4, 'Node.js');
INSERT INTO hackathon_tech (hackathon_id, position, tech) VALUES ('68ce896274267852dcc20716', 5, 'Express.js');

-- experience
INSERT INTO experience (id, role, company, company_url, employment_type, location, start_date, end_date, summary) VALUES ('e9c3e97da4f44ad8a8facfcd', 'Junior Network and Security Engineer', 'Ray Secure Innovations Private Limited', NULL, 'Full-time', 'Ahmedabad, Gujarat (On-site)', '2026-07', NULL, 'Moved into a permanent role in July 2026 after an eight-month internship, working on network infrastructure and security operations.');
INSERT INTO experience_skills (experience_id, position, skill) VALUES ('e9c3e97da4f44ad8a8facfcd', 0, 'Network Security');
INSERT INTO experience_skills (experience_id, position, skill) VALUES ('e9c3e97da4f44ad8a8facfcd', 1, 'Firewalls');
INSERT INTO experience_skills (experience_id, position, skill) VALUES ('e9c3e97da4f44ad8a8facfcd', 2, 'Routing & Switching');
INSERT INTO experience_skills (experience_id, position, skill) VALUES ('e9c3e97da4f44ad8a8facfcd', 3, 'VLANs');
INSERT INTO experience_skills (experience_id, position, skill) VALUES ('e9c3e97da4f44ad8a8facfcd', 4, 'Network Monitoring');
INSERT INTO experience (id, role, company, company_url, employment_type, location, start_date, end_date, summary) VALUES ('f3d1a0402e2854d81723d1ee', 'Network and Security Engineer Intern', 'Ray Secure Innovations Private Limited', NULL, 'Internship', 'Ahmedabad, Gujarat (On-site)', '2025-11', '2026-06', 'Eight-month internship across network infrastructure and security fundamentals, which converted into a full-time offer.');
INSERT INTO experience_skills (experience_id, position, skill) VALUES ('f3d1a0402e2854d81723d1ee', 0, 'Networking Fundamentals');
INSERT INTO experience_skills (experience_id, position, skill) VALUES ('f3d1a0402e2854d81723d1ee', 1, 'Network Security');
INSERT INTO experience_skills (experience_id, position, skill) VALUES ('f3d1a0402e2854d81723d1ee', 2, 'Troubleshooting');
